# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-17 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='longthesis',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='shortthesis',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
