# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='tickername',
            field=models.CharField(default='Asdasda', max_length=300),
            preserve_default=False,
        ),
    ]
